<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPublishable>false</IsPublishable>
    <IsPackable>false</IsPackable>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http.Client" />
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" VersionOverride="9.0.0" />
    <PackageReference Include="Grpc.Tools" VersionOverride="2.72.0" />
    <PackageReference Include="Polly.Core" VersionOverride="8.6.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" VersionOverride="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Catalog.API\Catalog.API.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
